services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: luxurioushc
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: luxuriousdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - luxurious-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: luxurioushc.om@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - luxurious-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      DATABASE_URL: postgres://luxurioushc:Admin@123@postgres:5432/luxuriousdb
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - luxurious-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://server:4000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - luxurious-network

volumes:
  pgdata:

networks:
  luxurious-network:
    driver: bridge
